---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0    # Use the ref you want to point at
      hooks:
          - id: check-yaml
          - id: sort-simple-yaml
          - id: trailing-whitespace

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0  # or higher tag
      hooks:
          - id: yamllint
            args: [-c=.yamllint]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11  # or specific tag
      hooks:
          - id: yamlfmt
